"""Assemble a deliverable zip from per-law artifacts.

Includes akn/, pdf/, txt/ and plain-text manifests and quality reports.
The quality report includes YAML frontmatter for downstream tooling.
"""

from __future__ import annotations

import io
import re
import zipfile
from dataclasses import dataclass, field

from lxml import etree

_TAG = re.compile(r"<[^>]+>")
_WS = re.compile(r"\s+")
# Grades whose body files ship. Mirror of the workflow's gate: an allow-list, so
# an unexpected or unvalidated grade is excluded, not admitted by omission.
_SHIPPABLE_GRADES = frozenset({"clean", "warning"})


@dataclass
class LawArtifacts:
    frbr_work_uri: str
    grade: str = "clean"
    # Grade-and-annotate: the translation's grade (A|B|C) and the review-tier
    # delivery findings (dropped money, lost provisions) so the report names
    # every law needing review, even when the export text is clean.
    translation_grade: str | None = None
    review_findings: list[str] = field(default_factory=list)
    # Provenance for the quality report ("show the work").
    source_id: str | None = None
    source_doctype: str | None = None
    # language code -> AKN XML / rendered PDF bytes
    akn_by_lang: dict[str, str] = field(default_factory=dict)
    pdf_by_lang: dict[str, bytes] = field(default_factory=dict)


def _slug(frbr_work_uri: str) -> str:
    """/akn/ps/act/decree-law/2018/37 -> ps-act-decree-law-2018-37 (filename-safe)."""
    body = re.sub(r"^/akn/", "", frbr_work_uri)
    return re.sub(r"[^a-z0-9]+", "-", body.lower()).strip("-")


def _plain_text(akn_xml: str) -> str:
    """Extract the AKN's text content. Parse it (it is valid by construction) and
    join the text nodes so entities decode (`&amp;` → `&`) and no markup leaks;
    fall back to a tag strip only if the fragment somehow will not parse."""
    try:
        root = etree.fromstring(akn_xml.encode("utf-8"))
        text = " ".join(root.itertext())
    except etree.XMLSyntaxError:
        text = _TAG.sub(" ", akn_xml)
    return _WS.sub(" ", text).strip()


def _quality_report(jurisdiction_code: str, laws: list[LawArtifacts], codify_version: str) -> str:
    order = {"clean": 0, "warning": 1, "blocking": 2, "failed": 3}
    ranked = sorted(laws, key=lambda law: (-order.get(law.grade, 0), law.frbr_work_uri))
    counts: dict[str, int] = {}
    tr_counts: dict[str, int] = {}
    review_count = 0
    for law in laws:
        counts[law.grade] = counts.get(law.grade, 0) + 1
        if law.translation_grade:
            tr_counts[law.translation_grade] = tr_counts.get(law.translation_grade, 0) + 1
        # Needs-a-human is the grade, not the presence of a review-tier delivery
        # row: translation grade C (whatever its cause, incl. an untranslated
        # paragraph the composite rubric hard-fails but delivery only flags
        # advisory) and a blocking structure both require review even with no
        # review-tier delivery finding attached.
        if law.translation_grade == "C" or law.grade == "blocking" or law.review_findings:
            review_count += 1
    lines = [
        "---",
        f"jurisdiction: {jurisdiction_code}",
        f"codify_version: {codify_version}",
        f"law_count: {len(laws)}",
        "grades:",
        *[f"  {g}: {n}" for g, n in sorted(counts.items())],
        "translation_grades:",
        *[f"  {g}: {n}" for g, n in sorted(tr_counts.items())],
        f"review_required: {review_count}",
        "---",
        "",
        "# Quality report",
        "",
        "Per-law structural and translation grade. `review_required` counts laws "
        "a human must check: translation grade C or a blocking structure. The "
        "`review` column names the specific silent legal-meaning risks (dropped "
        "money, lost provisions) where the delivery audit located one.",
        "",
        "| FRBR work URI | grade | translation | review | languages | source | doctype |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for law in ranked:
        langs = ",".join(sorted(law.akn_by_lang)) or "-"
        src = law.source_id or "-"
        doctype = law.source_doctype or "-"
        tr = law.translation_grade or "-"
        review = "; ".join(law.review_findings) if law.review_findings else "-"
        lines.append(
            f"| {law.frbr_work_uri} | {law.grade} | {tr} | {review} | {langs} | {src} | {doctype} |"
        )
    return "\n".join(lines) + "\n"


def _readme(
    jurisdiction_code: str,
    source_language: str,
    target_languages: list[str],
    laws: list[LawArtifacts],
    codify_version: str,
    render_pdf: bool = True,
) -> str:
    langs = ", ".join([source_language, *target_languages])
    lines = [
        f"# {jurisdiction_code.upper()} legislation deliverable",
        "",
        f"Generated by Codify {codify_version}.",
        f"Languages: {langs}.",
        f"Laws: {len(laws)}.",
        "",
        "## Layout",
        "  akn/   Akoma Ntoso 3.0 XML, one file per law per language",
        *(
            ["  pdf/   rendered PDF, one file per law per language"]
            if render_pdf
            else ["  (pdf/ omitted — PDF rendering was disabled for this run)"]
        ),
        "  txt/   plain-text UTF-8 dump per law per language",
        "  quality-report.txt   per-law structural grade (YAML frontmatter + table)",
        "  manifest.txt         every law assessed (see quality-report.txt for which shipped)",
        "",
        "## Laws",
    ]
    lines += [f"  {law.frbr_work_uri}" for law in laws]
    return "\n".join(lines) + "\n"


def build_deliverable(
    *,
    jurisdiction_code: str,
    source_language: str,
    target_languages: list[str],
    laws: list[LawArtifacts],
    codify_version: str,
    include_blocking: bool = False,
    render_pdf: bool = True,
) -> tuple[bytes, str]:
    """Return (zip_bytes, quality_report_text). Only clean/warning laws reach the
    body; blocking/failed still appear in the quality report. ``include_blocking``
    admits blocking-structural laws to the body (translated + graded-C, opt-in per
    run); it must match the workflow's own eligibility gate or those laws are
    translated then silently dropped here. ``render_pdf=False`` means the export
    stage was parked, so there is no ``pdf/`` directory and the README says so."""
    shippable = _SHIPPABLE_GRADES | {"blocking"} if include_blocking else _SHIPPABLE_GRADES
    report = _quality_report(jurisdiction_code, laws, codify_version)
    readme = _readme(
        jurisdiction_code,
        source_language,
        target_languages,
        laws,
        codify_version,
        render_pdf,
    )
    manifest = "\n".join(law.frbr_work_uri for law in laws) + "\n"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("README.txt", readme)
        z.writestr("quality-report.txt", report)
        z.writestr("manifest.txt", manifest)
        for law in laws:
            if law.grade not in shippable:
                continue  # named in the report, kept out of the body
            slug = _slug(law.frbr_work_uri)
            for lang, akn in law.akn_by_lang.items():
                z.writestr(f"akn/{slug}.{lang}.xml", akn)
                z.writestr(f"txt/{slug}.{lang}.txt", _plain_text(akn))
            for lang, pdf in law.pdf_by_lang.items():
                z.writestr(f"pdf/{slug}.{lang}.pdf", pdf)
    return buf.getvalue(), report


if __name__ == "__main__":
    # ponytail: smallest check that the zip assembles and the gate holds.
    laws = [
        LawArtifacts(
            "/akn/ps/act/decree-law/2018/37",
            "clean",
            akn_by_lang={"ara": "<akn><p>نص</p></akn>"},
            pdf_by_lang={"ara": b"%PDF-1.4 fake"},
        ),
        LawArtifacts("/akn/ps/act/decree-law/2012/4", "blocking", akn_by_lang={"ara": "<akn/>"}),
    ]
    z, report = build_deliverable(
        jurisdiction_code="ps",
        source_language="ara",
        target_languages=["en"],
        laws=laws,
        codify_version="test",
    )
    names = set(zipfile.ZipFile(io.BytesIO(z)).namelist())
    assert "akn/ps-act-decree-law-2018-37.ara.xml" in names, names
    assert "pdf/ps-act-decree-law-2018-37.ara.pdf" in names, names
    assert not any("2012-4" in n for n in names), "blocking law must be excluded from body"
    assert "blocking: 1" in report and "clean: 1" in report
    print("packager self-check ok:", len(names), "entries")
