/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jurisdictions */
        get: operations["jurisdictions_jurisdictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jurisdictions/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jurisdiction */
        get: operations["jurisdiction_jurisdictions__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jurisdictions/{code}/laws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laws For */
        get: operations["laws_for_jurisdictions__code__laws_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laws */
        get: operations["laws_laws_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laws/{law_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Law */
        get: operations["law_laws__law_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_runs_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/ingest-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Url */
        post: operations["ingest_url_runs_ingest_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run State */
        get: operations["run_state_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Stream */
        get: operations["run_stream_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AknSource
         * @description One upstream that yields documents convertible to AKN.
         *
         *     Distinct from `SourceAdapter`, the acquisition substrate keyed by adapter kind:
         *     this is a format-and-protocol pairing declared in `config.json#akn_sources`.
         *     Both coexist during the schema migration and `effective_tier` walks both; legacy
         *     configs without `format`/`protocol` default to PDF over HTTP.
         */
        AknSource: {
            /**
             * Auth Env Var
             * @default
             */
            auth_env_var: string;
            /**
             * Auth Scheme
             * @default none
             * @enum {string}
             */
            auth_scheme: "none" | "token" | "bearer" | "api_key" | "operator_code" | "basic" | "soap_session" | "email_registration";
            /**
             * Coverage
             * @default unknown
             * @enum {string}
             */
            coverage: "complete" | "partial" | "stub" | "unknown";
            /** Coverage Note */
            coverage_note?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Fallback Format */
            fallback_format?: ("akn_xml" | "akn_xml_v2" | "bespoke_xml" | "structured_html" | "html" | "pdf" | "pdf_scanned" | "docx" | "rtf" | "json" | "csv" | "rdf") | null;
            /**
             * Format
             * @default pdf
             * @enum {string}
             */
            format: "akn_xml" | "akn_xml_v2" | "bespoke_xml" | "structured_html" | "html" | "pdf" | "pdf_scanned" | "docx" | "rtf" | "json" | "csv" | "rdf";
            /** License */
            license?: string | null;
            /** Name */
            name: string;
            /**
             * Protocol
             * @default http
             * @enum {string}
             */
            protocol: "http" | "rest" | "odata" | "sru" | "oai_pmh" | "soap" | "sparql" | "bulk_dump";
            /**
             * Requires Token
             * @default false
             */
            requires_token: boolean;
            /** Schema Id */
            schema_id?: string | null;
            /** Schema Url */
            schema_url?: string | null;
            /** Url Template */
            url_template: string;
        };
        /** AmendmentConfig */
        AmendmentConfig: {
            /** Amending Body Structure */
            amending_body_structure?: string | null;
            /** Amendment Item Kind */
            amendment_item_kind?: string | null;
            /** Cross Reference Format */
            cross_reference_format?: string | null;
            /** Phrasing */
            phrasing?: string | null;
            /** Style */
            style?: string | null;
            /** Trigger Phrases */
            trigger_phrases?: string[];
        } & {
            [key: string]: unknown;
        };
        /**
         * AttachmentCaption
         * @description A caption line opening an attachment. AKN models a schedule and a
         *     mandatory companion alike, so legal force is declared per caption.
         */
        AttachmentCaption: {
            /** Caption */
            caption: string;
            /** Hierarchy */
            hierarchy?: components["schemas"]["HierarchyEntry"][];
            /**
             * Normative
             * @default true
             */
            normative: boolean;
            /**
             * Prefix
             * @default false
             */
            prefix: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * BindingRegime
         * @description Non-membership binding regime, treaty frameworks, bilateral regimes,
         *     constitutional annexes. Used for things like the Dayton Framework (BA),
         *     the Compact of Free Association (PW/MH), and the Lateran Concordat (VA)
         *     which are legally binding on a jurisdiction but are not memberships in an
         *     international organisation.
         */
        BindingRegime: {
            /** Code */
            code: string;
            /**
             * Direct Effect
             * @default none
             * @enum {string}
             */
            direct_effect: "override" | "direct" | "indirect_transposition" | "procedural" | "operational" | "advisory" | "none";
            /** In Force From */
            in_force_from?: string | null;
            /** In Force Until */
            in_force_until?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "treaty_framework" | "bilateral_regime" | "constitutional_annex" | "security_council_resolution";
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Renewable
             * @default false
             */
            renewable: boolean;
            /** Reporting Cadence */
            reporting_cadence?: ("monthly" | "quarterly" | "six_monthly" | "annual" | "ad_hoc") | null;
            /** Superseded Subjects */
            superseded_subjects?: string[];
            /** Territories */
            territories?: string[];
        };
        /** Body_ingest_runs_ingest_post */
        Body_ingest_runs_ingest_post: {
            /** File */
            file: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Title */
            title?: string | null;
        };
        /**
         * CalendarConversion
         * @description Deterministic conversion rule for non-Gregorian local calendars.
         *
         *     kind selects which optional fields apply:
         *
         *     - epoch_offset  single-epoch calendars. Gregorian = local_year + epoch_year,
         *                     where epoch_year is an integer offset (ROC 1911, Juche 1911,
         *                     Buddhist -543).
         *     - era_table     named era segments with boundaries.
         *     - hijri_lunar   Islamic Hijri, ~354 days. Needs codify.calendar, not an offset.
         *     - hijri_solar   Iranian Hijri, Gregorian year length.
         *     - ethiopian     ~7-8 year offset, 13-month year.
         *     - buddhist      Thai/Lao, epoch_year -543.
         *     - bikram_samvat Nepali, 57-year offset, month-sensitive (Chaitra straddles the
         *                     mid-April new year).
         */
        CalendarConversion: {
            /** Date Cues */
            date_cues?: string[];
            /** Epoch Year */
            epoch_year?: number | null;
            /** Eras */
            eras?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "epoch_offset" | "era_table" | "hijri_lunar" | "hijri_solar" | "ethiopian" | "buddhist" | "bikram_samvat";
            /**
             * Month Day Is Gregorian
             * @default false
             */
            month_day_is_gregorian: boolean;
            /** Month Names */
            month_names?: string[];
            /** New Year Day */
            new_year_day?: number | null;
            /** New Year Month */
            new_year_month?: number | null;
            /** New Year Reform Year */
            new_year_reform_year?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
            /** Offset */
            offset?: number | null;
            /** Year Particles */
            year_particles?: string[];
        };
        /** Cancelled */
        Cancelled: {
            /**
             * Cancelled
             * Format: uuid
             */
            cancelled: string;
        };
        /**
         * ClassificationRule
         * @description Deterministic rule for assigning a document class from the incoming header or
         *     metadata. Tried in descending priority; the first match wins. No match falls back to
         *     `default_document_class` and to whatever heuristics `StructuringConfig.prompt_additions`
         *     still carries.
         *
         *     signal          what `pattern` is tested against
         *       date_range      nothing; the match is `date_from`/`date_until` alone, for laws
         *                       post-dating a regime change (PS `qarar_bi_qanun` from 2007-06-14)
         *       preamble_match  the preamble or enacting-formula text
         *       issuer_role     the enacting body's role ("Pope", "Council of Ministers", "OHR")
         *       gazette_series  the official gazette series the document was published in
         *       title_regex     the document title ("Basic Law:", "Motu Proprio")
         */
        ClassificationRule: {
            /** Date From */
            date_from?: string | null;
            /** Date Until */
            date_until?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Pattern
             * @default
             */
            pattern: string;
            /**
             * Pattern Flags
             * @default
             */
            pattern_flags: string;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /**
             * Signal
             * @enum {string}
             */
            signal: "date_range" | "preamble_match" | "issuer_role" | "gazette_series" | "title_regex";
            /** Target Document Class */
            target_document_class: string;
        };
        /**
         * DiscoveryConfig
         * @description Config-driven discovery for adapters that support it. The *basket
         *     definition* (which acts to find) lives here as per-doctype query strings;
         *     the portal mechanics (request shape, facets) stay in the adapter.
         */
        DiscoveryConfig: {
            /**
             * Max Total
             * @default 5000
             */
            max_total: number;
            /** Output */
            output?: string | null;
            /** Queries */
            queries?: {
                [key: string]: string;
            };
        };
        /** DisplayConfig */
        DisplayConfig: {
            /** Amendment Markers */
            amendment_markers?: string[];
            /**
             * Font Preference
             * @default serif
             */
            font_preference: string;
            /**
             * Heading Case
             * @default title_case
             */
            heading_case: string;
            /**
             * Heading Type
             * @default marginal_note
             */
            heading_type: string;
            /**
             * Rtl
             * @default false
             */
            rtl: boolean;
            /**
             * Script
             * @default latin
             */
            script: string;
        } & {
            [key: string]: unknown;
        };
        /** DocumentClass */
        DocumentClass: {
            /**
             * Akn Element
             * @default act
             */
            akn_element: string;
            /** Akn Subtype */
            akn_subtype?: string | null;
            /** Authoritative Language */
            authoritative_language?: string | null;
            /**
             * Basic Unit
             * @default section
             */
            basic_unit: string;
            /**
             * Bluebell Compatible
             * @default true
             */
            bluebell_compatible: boolean;
            /** Direct Effect */
            direct_effect?: boolean | null;
            /** Extends */
            extends?: string | null;
            /** Frbr Subtype */
            frbr_subtype?: string | null;
            /** Hcontainers */
            hcontainers?: components["schemas"]["HContainer"][];
            /** Hierarchy */
            hierarchy?: components["schemas"]["HierarchyEntry"][];
            /** Label */
            label: string;
            /** Local Label */
            local_label?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Number Has Year Prefix
             * @default false
             */
            number_has_year_prefix: boolean;
            /** Prompt Variant */
            prompt_variant?: string | null;
            /** Search Rank */
            search_rank?: number | null;
            /** Short Label */
            short_label?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** EnactingFormula */
        EnactingFormula: {
            /** Applies To */
            applies_to?: unknown[] | string | null;
            /** Document Class */
            document_class?: string | string[] | null;
            /** Enacting Body Tlc */
            enacting_body_tlc?: string | null;
            /**
             * Era
             * @default
             */
            era: string;
            /** From */
            from?: string | null;
            /** Instrument Type */
            instrument_type?: string | null;
            /** Language */
            language?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Position
             * @default preamble
             */
            position: string;
            /** Text */
            text?: string | null;
            /** To */
            to?: string | null;
            /** Transliteration */
            transliteration?: string | null;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        } & {
            [key: string]: unknown;
        };
        /** FrbrConfig */
        FrbrConfig: {
            calendar_conversion?: components["schemas"]["CalendarConversion"] | null;
            /** Country Code */
            country_code: string;
            /**
             * Date Calendar
             * @default gregorian
             * @enum {string}
             */
            date_calendar: "gregorian" | "lunar_hijri" | "solar_hijri" | "ethiopian" | "japanese_era" | "minguo" | "buddhist_era" | "dual";
            /** Date Calendar Note */
            date_calendar_note?: string | null;
            /** Note */
            note?: string | null;
            /** Notes */
            notes?: string[] | string | null;
            /** Number Extraction */
            number_extraction?: string | {
                [key: string]: unknown;
            } | null;
            /** Number Format */
            number_format?: string | {
                [key: string]: string;
            } | null;
            /** Number Note */
            number_note?: string | null;
            /** Sample Uris */
            sample_uris?: unknown[] | {
                [key: string]: string;
            } | null;
            title_identity?: components["schemas"]["TitleIdentity"] | null;
            /** Uri Patterns */
            uri_patterns?: {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** HContainer */
        HContainer: {
            /** Akn Element */
            akn_element?: ("book" | "part" | "title" | "subtitle" | "tome" | "chapter" | "subchapter" | "section" | "subsection" | "division" | "subdivision" | "subpart" | "article" | "paragraph" | "subparagraph" | "clause" | "subclause" | "point" | "indent" | "alinea" | "rule" | "subrule" | "item" | "attachment" | "hcontainer" | "proviso") | null;
            /** Bluebell Keyword */
            bluebell_keyword?: ("BOOK" | "PART" | "TITLE" | "SUBTITLE" | "TOME" | "CHAPTER" | "SUBCHAPTER" | "SECTION" | "SUBSECTION" | "DIVISION" | "SUBDIVISION" | "SUBPART" | "ARTICLE" | "PARAGRAPH" | "SUBPARAGRAPH" | "CLAUSE" | "SUBCLAUSE" | "POINT" | "INDENT" | "ALINEA" | "RULE" | "SUBRULE" | "PROVISO" | "TRANSITIONAL" | "CROSSHEADING" | "PART_HEADING") | null;
            /**
             * Bluebell Proxy
             * @default SUBSECTION
             * @enum {string}
             */
            bluebell_proxy: "BOOK" | "PART" | "TITLE" | "SUBTITLE" | "TOME" | "CHAPTER" | "SUBCHAPTER" | "SECTION" | "SUBSECTION" | "DIVISION" | "SUBDIVISION" | "SUBPART" | "ARTICLE" | "PARAGRAPH" | "SUBPARAGRAPH" | "CLAUSE" | "SUBCLAUSE" | "POINT" | "INDENT" | "ALINEA" | "RULE" | "SUBRULE" | "PROVISO" | "TRANSITIONAL" | "CROSSHEADING" | "PART_HEADING";
            /**
             * Description
             * @default
             */
            description: string;
            /** Label */
            label?: string | null;
            /** Level */
            level?: string | null;
            /** Local Term */
            local_term: string;
            /** Name */
            name: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Numbering */
            numbering?: string | null;
            /** Position */
            position?: string | null;
            /**
             * Requires Postprocessing
             * @default true
             */
            requires_postprocessing: boolean;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HierarchyEntry */
        HierarchyEntry: {
            /**
             * Akn Element
             * @enum {string}
             */
            akn_element: "book" | "part" | "title" | "subtitle" | "tome" | "chapter" | "subchapter" | "section" | "subsection" | "division" | "subdivision" | "subpart" | "article" | "paragraph" | "subparagraph" | "clause" | "subclause" | "point" | "indent" | "alinea" | "rule" | "subrule" | "item" | "attachment" | "hcontainer" | "proviso";
            /** Akn Name */
            akn_name?: string | null;
            /** Bluebell Keyword */
            bluebell_keyword?: ("BOOK" | "PART" | "TITLE" | "SUBTITLE" | "TOME" | "CHAPTER" | "SUBCHAPTER" | "SECTION" | "SUBSECTION" | "DIVISION" | "SUBDIVISION" | "SUBPART" | "ARTICLE" | "PARAGRAPH" | "SUBPARAGRAPH" | "CLAUSE" | "SUBCLAUSE" | "POINT" | "INDENT" | "ALINEA" | "RULE" | "SUBRULE" | "PROVISO" | "TRANSITIONAL" | "CROSSHEADING" | "PART_HEADING") | null;
            /** Captions */
            captions?: string[];
            /**
             * Eid Abbrev
             * @default
             */
            eid_abbrev: string;
            /**
             * Level
             * @enum {string}
             */
            level: "higher" | "basic" | "subdivision" | "grouping" | "presentational";
            /** Local Term */
            local_term: string;
            /** Local Terms */
            local_terms?: {
                [key: string]: string;
            } | null;
            /** Marker Form */
            marker_form?: ("caption" | "bracketed_decimal" | "upper_letter_period" | "upper_roman_period" | "lower_letter_period" | "arabic_period" | "arabic_closing_paren" | "lower_letter_closing_paren" | "parenthesized_arabic") | null;
            /**
             * Note
             * @default
             */
            note: string;
            /** Numbering */
            numbering?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** IdentificationConfig */
        IdentificationConfig: {
            /**
             * Eli Base
             * @default
             */
            eli_base: string;
            /**
             * Pattern
             * @default
             */
            pattern: string;
            /**
             * System
             * @default
             */
            system: string;
        } & {
            [key: string]: unknown;
        };
        /** IngestUrl */
        IngestUrl: {
            /** Jurisdiction */
            jurisdiction: string;
            /** Title */
            title?: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** JurisdictionConfig */
        JurisdictionConfig: {
            /** Adoption Markers */
            adoption_markers?: string[];
            /** Akn Profile */
            akn_profile?: string | null;
            /** Akn Sources */
            akn_sources?: components["schemas"]["AknSource"][];
            amendments?: components["schemas"]["AmendmentConfig"] | null;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentCaption"][];
            /** Authoritative Language */
            authoritative_language?: string | null;
            /** Binding Regimes */
            binding_regimes?: components["schemas"]["BindingRegime"][];
            /**
             * Calendar
             * @default gregorian
             * @enum {string}
             */
            calendar: "gregorian" | "lunar_hijri" | "solar_hijri" | "ethiopian" | "japanese_era" | "minguo" | "buddhist_era" | "dual";
            /** Closing Phrases */
            closing_phrases?: string[];
            /** Code */
            code: string;
            /** Core Tlcs */
            core_tlcs?: components["schemas"]["TLCEntry"][];
            /**
             * Coverage Status
             * @default in_scope
             * @enum {string}
             */
            coverage_status: "in_scope" | "subsumed" | "no_corpus" | "deferred";
            /**
             * Default Document Class
             * @default act
             */
            default_document_class: string;
            display?: components["schemas"]["DisplayConfig"] | null;
            /** Document Classes */
            document_classes?: {
                [key: string]: components["schemas"]["DocumentClass"];
            };
            /**
             * Effective Tier
             * @description Tier actually achievable in the current environment.
             *
             *     Walks both `source_adapters` and the legacy `akn_sources`, taking the best
             *     (lowest) tier. Token-gated entries with an unset env var are skipped unless the
             *     source declares a `fallback_format`, whose tier contributes instead.
             */
            readonly effective_tier: (1 | 2 | 3 | 4 | 5) | null;
            /** Enacting Formula Markers */
            enacting_formula_markers?: string[];
            /** Enacting Formulae */
            enacting_formulae?: components["schemas"]["EnactingFormula"][];
            /** Footnote Markers */
            footnote_markers?: string[];
            frbr?: components["schemas"]["FrbrConfig"] | null;
            /** Furniture Inline Patterns */
            furniture_inline_patterns?: string[];
            /** Furniture Line Patterns */
            furniture_line_patterns?: string[];
            identification?: components["schemas"]["IdentificationConfig"] | null;
            /** Languages */
            languages: string[];
            /** Legal Eras */
            legal_eras?: components["schemas"]["LegalEra"][];
            /** Lexicon Words */
            lexicon_words?: string[];
            /** Members */
            members?: string[];
            /**
             * Min Anchor Coverage
             * @default 0.8
             */
            min_anchor_coverage: number;
            /** Name */
            name: string;
            /** Name En */
            name_en?: string | null;
            /** Name Local */
            name_local?: string | null;
            /** Name Translations */
            name_translations?: {
                [key: string]: string;
            };
            /**
             * Note
             * @default
             */
            note: string;
            numbering?: components["schemas"]["NumberingConfig"] | null;
            /** Ocr Header Patterns */
            ocr_header_patterns?: string[];
            /** Opening Material Terminators */
            opening_material_terminators?: string[];
            /** Placeholders */
            placeholders?: components["schemas"]["PlaceholderMarker"][];
            /**
             * Public Reference
             * @default false
             */
            public_reference: boolean;
            /** Residual Legal Systems */
            residual_legal_systems?: components["schemas"]["ResidualLaw"][];
            /** Source Adapters */
            source_adapters?: components["schemas"]["SourceAdapter"][];
            /**
             * Source Truncation Floor
             * @default 0
             */
            source_truncation_floor: number;
            /** Status */
            status?: ("production" | "draft" | "stub") | null;
            structuring?: components["schemas"]["StructuringConfig"] | null;
            /** Subsumed By */
            subsumed_by?: string | null;
            /** Supranational Memberships */
            supranational_memberships?: components["schemas"]["SupranationalMembership"][];
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /** Tier */
            tier?: (1 | 2 | 3 | 4 | 5) | null;
            /** Tradition */
            tradition: ("civil_law" | "common_law" | "islamic" | "customary" | "hindu" | "confucian" | "jewish" | "socialist" | "sui_generis")[];
            /**
             * Type
             * @default national
             * @enum {string}
             */
            type: "national" | "supranational" | "subnational" | "crown_dependency";
            validation?: components["schemas"]["ValidationConfig"] | null;
        } & {
            [key: string]: unknown;
        };
        /** JurisdictionSummary */
        JurisdictionSummary: {
            /** Code */
            code: string;
            /** Languages */
            languages: string[];
            /** Name */
            name: string;
        };
        /** LawDetail */
        LawDetail: {
            /** Doctype */
            doctype: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Number */
            number: string | null;
            /** Short Title */
            short_title: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
            /** Work Uri */
            work_uri: string;
            /** Year */
            year: number | null;
        };
        /** LawPage */
        LawPage: {
            /** Items */
            items: components["schemas"]["LawSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * LawSummary
         * @description Listing-friendly projection of a Law row. `lens_coverage` is opt-in: the
         *     corpus-wide `/laws` route always populates it, the per-jurisdiction listing
         *     only on `?include=coverage`, and callers that skip it read `None`.
         */
        LawSummary: {
            /** Doctype */
            doctype: string;
            /** Frbr Work Uri */
            frbr_work_uri: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jurisdiction Code */
            jurisdiction_code: string;
            /** Latest Expression Date */
            latest_expression_date: string | null;
            /** Latest Ingested At */
            latest_ingested_at?: string | null;
            /** Lens Coverage */
            lens_coverage?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /** Number */
            number: string | null;
            /** Short Title */
            short_title?: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Title Translations
             * @default {}
             */
            title_translations: {
                [key: string]: string;
            };
            /** Year */
            year: number | null;
        };
        /**
         * LegalEra
         * @description A period whose documents share a drafting convention and authority.
         *
         *     Structural quality tracks era more than jurisdiction, so it is reported per era.
         *     ``from_``/``to`` are inclusive ISO dates, either may be open, and the field is
         *     spelled ``from`` in the config files.
         */
        LegalEra: {
            /** Authority Patterns */
            authority_patterns?: string[];
            /** Calendar */
            calendar?: ("gregorian" | "lunar_hijri" | "solar_hijri" | "ethiopian" | "japanese_era" | "minguo" | "buddhist_era" | "dual") | null;
            /** Closing Phrases */
            closing_phrases?: string[];
            /**
             * Document Class
             * @default
             */
            document_class: string;
            /**
             * Enacting Authority
             * @default
             */
            enacting_authority: string;
            /** Footnote Markers */
            footnote_markers?: string[];
            /** From */
            from?: string | null;
            /** Id */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** To */
            to?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** NumberingConfig */
        NumberingConfig: {
            /** Act Citation */
            act_citation?: string | null;
            /** Act Citation Alt */
            act_citation_alt?: string | null;
            /** Article Numbering */
            article_numbering?: string | null;
            /** Citations */
            citations?: {
                [key: string]: string;
            };
            /** Insertion Example */
            insertion_example?: string | null;
            /** Insertion Note */
            insertion_note?: string | null;
            /** Insertion Style */
            insertion_style?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Numbers Unique Across Years
             * @default false
             */
            numbers_unique_across_years: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * PlaceholderMarker
         * @description A whole-string pattern a publisher writes where content is missing or
         *     struck, and the AKN status the unit should carry for it.
         */
        PlaceholderMarker: {
            /** Pattern */
            pattern: string;
            /** @default incomplete */
            status: components["schemas"]["PlaceholderStatus"];
        };
        /**
         * PlaceholderStatus
         * @description The AKN `@status` a placeholder unit should carry; named so the generated
         *     contract keeps a stable alias rather than a numbered `Status`.
         * @enum {string}
         */
        PlaceholderStatus: "incomplete" | "removed" | "editorial";
        /**
         * ResidualLaw
         * @description Another jurisdiction's corpus that is still residually applicable here.
         *
         *     Used for layered legal systems where pre-independence or foreign law
         *     continues in force alongside native legislation. Examples:
         *       - VA: Italian law as suppletive in Vatican City State.
         *       - SY, IQ, LB: Ottoman Mejelle for general private law.
         *       - ZA, LS, SZ, NA: Roman-Dutch common law (but usually too embedded
         *             to carve out as discrete residuals).
         *
         *     `source_jurisdiction` is a Codify code that must resolve to an existing
         *     config. Downstream consolidation/amendment agents can traverse these to
         *     find the source corpus.
         */
        ResidualLaw: {
            /** In Force From */
            in_force_from?: string | null;
            /** In Force Until */
            in_force_until?: string | null;
            /** Label */
            label: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "territorial" | "subject_matter" | "personal_status" | "general";
            /** Source Jurisdiction */
            source_jurisdiction: string;
            /** Subjects */
            subjects?: string[];
            /** Superseded By */
            superseded_by?: string[];
            /** Territories */
            territories?: string[];
        };
        /** RunSnapshot */
        RunSnapshot: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Events */
            events: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Lost On Restart */
            lost_on_restart: boolean;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Retry Of */
            retry_of: string | null;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        };
        /** SearchMatch */
        SearchMatch: {
            /** Eid */
            eid: string;
            /**
             * Provision Id
             * Format: uuid
             */
            provision_id: string;
            /** Score */
            score: number;
            /** Text */
            text: string;
        };
        /** SearchResult */
        SearchResult: {
            /** Matches */
            matches: components["schemas"]["SearchMatch"][];
            /** Query */
            query: string;
        };
        /**
         * SourceAdapter
         * @description One upstream portal for this jurisdiction; multiple permitted.
         *
         *     url_template placeholders: {country} {doctype} {year} {number} {frbr_uri}. Auth
         *     tokens resolve from the env var named by auth_env_var, never stored here.
         */
        SourceAdapter: {
            /**
             * Auth Env Var
             * @default
             */
            auth_env_var: string;
            /**
             * Auth Scheme
             * @default none
             * @enum {string}
             */
            auth_scheme: "none" | "token" | "bearer" | "oauth";
            /** Base Url */
            base_url?: string | null;
            discovery?: components["schemas"]["DiscoveryConfig"] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "akn_native" | "eurlex_cellar" | "html_portal" | "pdf_gazette" | "paragraf_propisi" | "sparql" | "bulk_xml_archive";
            /** Licence */
            licence?: string | null;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Parser */
            parser?: string | null;
            /** Rate Limit Per Minute */
            rate_limit_per_minute?: number | null;
            /**
             * Robots Respect
             * @default true
             */
            robots_respect: boolean;
            /** Url Template */
            url_template?: string | null;
        };
        /** StructuringConfig */
        StructuringConfig: {
            /**
             * Body Opens With Container
             * @default false
             */
            body_opens_with_container: boolean;
            /**
             * Citation Articles
             * @description Articles that may sit between the clause and the name (`the`). Language data: most languages have none, and no article is assumed.
             */
            citation_articles?: string[];
            /**
             * Citation Lead Ins
             * @description Phrases introducing a law's own short name (`may be cited as`), the common-law short-title device.
             */
            citation_lead_ins?: string[];
            /**
             * Citation Subjects
             * @description How an instrument refers to itself when it declares its short name (`This Act`). Required alongside `citation_lead_ins`: the same phrasing names the schools and offices a law creates, so an unanchored clause takes the school's name for the law's.
             */
            citation_subjects?: string[];
            /** Citation Successors */
            citation_successors?: string[];
            /** Classification Rules */
            classification_rules?: components["schemas"]["ClassificationRule"][];
            /**
             * Designation Rule
             * @description Derives a short name from the title's own grammar where the tradition declares no short title. EU acts are cited by form and number.
             */
            designation_rule?: "eu_instrument" | null;
            /**
             * Example Markers
             * @description Lead-ins that introduce specimen legislation in a drafting manual (`Contoh`), whose markers are displayed rather than enacted.
             */
            example_markers?: string[];
            /** Insertion Suffixes */
            insertion_suffixes?: {
                [key: string]: string;
            };
            /**
             * Long Title Lead Ins
             * @description Openings of the document's own long title (`An Act`), marked up as `<longTitle>` so the official title comes from the text rather than from a filename.
             */
            long_title_lead_ins?: string[];
            /**
             * Marker Boundary
             * @default relaxed
             * @enum {string}
             */
            marker_boundary: "relaxed" | "line_anchored";
            /** Marker Tolerances */
            marker_tolerances?: ("missing_separator" | "keyword_glyph" | "digit_glyph" | "split_number")[];
            /** Ordinal Words */
            ordinal_words?: {
                [key: string]: number;
            };
            /** Prompt Additions */
            prompt_additions?: string | null;
            /** Prompt Variant */
            prompt_variant?: string | null;
            /** Prose Precursors */
            prose_precursors?: string[];
            /** Reference Nouns */
            reference_nouns?: string[];
            /** Sameline Precursors */
            sameline_precursors?: string[];
        } & {
            [key: string]: unknown;
        };
        /** SupranationalMembership */
        SupranationalMembership: {
            /** Body */
            body: string;
            /**
             * Direct Effect
             * @default none
             * @enum {string}
             */
            direct_effect: "override" | "direct" | "indirect_transposition" | "procedural" | "operational" | "advisory" | "none";
            /** Direct Effect Instruments */
            direct_effect_instruments?: string[];
            /** Direct Effect Note */
            direct_effect_note?: string | null;
            /** Excluded Instruments */
            excluded_instruments?: string[];
            /** Excluded Subjects */
            excluded_subjects?: string[];
            /** Member Since */
            member_since?: string | null;
            /** Member Until */
            member_until?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
            /** Protocol References */
            protocol_references?: string[];
            /** Rejoined On */
            rejoined_on?: string | null;
            /** Status */
            status?: ("member" | "suspended" | "former" | "candidate" | "potential_candidate" | "associate" | "observer" | "special_status" | "never_member") | null;
            /** Superseded Subjects */
            superseded_subjects?: string[];
            /** Suspension Periods */
            suspension_periods?: components["schemas"]["SuspensionPeriod"][];
            /** Transposition Required */
            transposition_required?: boolean | string[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SuspensionPeriod
         * @description One period of suspension from a supranational body.
         *
         *     Used inside `SupranationalMembership.suspension_periods` to record the
         *     start and (optional) end of a suspension, plus its scope. A list is the
         *     right shape because several jurisdictions have cycled through multiple
         *     suspensions (Fiji at the PIF/Commonwealth; Pakistan at the Commonwealth;
         *     coup states at AU/ECOWAS).
         */
        SuspensionPeriod: {
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Scope
             * @default full
             * @enum {string}
             */
            scope: "full" | "decision_making" | "meetings" | "voting";
            /** Suspended From */
            suspended_from: string;
            /** Suspended Until */
            suspended_until?: string | null;
        };
        /** TLCEntry */
        TLCEntry: {
            /**
             * Class
             * @enum {string}
             */
            class: "TLCPerson" | "TLCOrganization" | "TLCRole" | "TLCObject" | "TLCConcept" | "TLCEvent" | "TLCLocation" | "TLCProcess" | "TLCTerm" | "TLCReference";
            /** Eid */
            eId: string;
            /** Href */
            href: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Showas */
            showAs: string;
        };
        /**
         * TitleIdentity
         * @description How a jurisdiction that numbers nothing derives an identity from a title.
         *     Every field is a literal `codify.frbr.identity_from_title` reads.
         */
        TitleIdentity: {
            /** Consolidation Markers */
            consolidation_markers?: string[];
            /** Edition Markers */
            edition_markers?: string[];
            /** Strip Prefixes */
            strip_prefixes?: string[];
            /** Year Particles */
            year_particles?: string[];
        };
        /** ValidationConfig */
        ValidationConfig: {
            /** Ambiguities */
            ambiguities?: string[];
            /**
             * Bluebell Tested
             * @default false
             */
            bluebell_tested: boolean;
            /**
             * Documents Examined
             * @default 0
             */
            documents_examined: number;
            /** Documents Examined Note */
            documents_examined_note?: string | null;
            /** Laws Africa Reference */
            laws_africa_reference?: string | boolean | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "production" | "draft" | "stub";
            /**
             * Unresolved Ambiguities
             * @default 0
             */
            unresolved_ambiguities: number;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionDetail */
        VersionDetail: {
            /** Akn Xml */
            akn_xml: string;
            /** Expression Date */
            expression_date: string | null;
            /** Expression Uri */
            expression_uri: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ingested At */
            ingested_at: string | null;
            /** Language */
            language: string;
            /**
             * Law Id
             * Format: uuid
             */
            law_id: string;
            /** Structural Quality Grade */
            structural_quality_grade: string | null;
        };
        /** VersionSummary */
        VersionSummary: {
            /** Expression Date */
            expression_date: string | null;
            /** Expression Uri */
            expression_uri: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ingested At */
            ingested_at: string | null;
            /** Language */
            language: string;
            /**
             * Law Id
             * Format: uuid
             */
            law_id: string;
            /** Structural Quality Grade */
            structural_quality_grade: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    jurisdictions_jurisdictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JurisdictionSummary"][];
                };
            };
        };
    };
    jurisdiction_jurisdictions__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JurisdictionConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    laws_for_jurisdictions__code__laws_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    laws_laws_get: {
        parameters: {
            query?: {
                jurisdiction?: string | null;
                doctype?: string | null;
                year?: number | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    law_laws__law_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"][];
                };
            };
        };
    };
    ingest_runs_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_runs_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_url_runs_ingest_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestUrl"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_state_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancelled"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                jurisdiction: string;
                k?: number;
                language?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
